title: >
    Reparaciones Murcia
email: >
    your-email@domain.com
description: >
    

baseurl: "/"
url: http://keralahost.in/omardubiren
google_adsense: Your-adsense-code

markdown: kramdown

name: >
    Reparaciones Murcia

date: 2019-03-21 01:36:53 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/omardubiren/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: >
    
author_image: >
    

author: >
    omardubiren
